// Generated by scripts/generate-abi.mjs. Do not edit manually.

export const ABI = [
  {
    "type": "error",
    "name": "ActiveDispute",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AlreadyRuled",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AlreadySubmitted",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AppealWindowNotOpen",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CannotRemoveDefaultImplementation",
    "inputs": [
      {
        "name": "implementation",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "DisputeAlreadyExists",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "DisputeNotFound",
    "inputs": [
      {
        "name": "providerDisputeId",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "EmptyURI",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Error",
    "inputs": [
      {
        "name": "message",
        "type": "string"
      }
    ]
  },
  {
    "type": "error",
    "name": "FailedDeployment",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ImplementationAlreadyExists",
    "inputs": [
      {
        "name": "implementation",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ImplementationNotRegistered",
    "inputs": [
      {
        "name": "implementation",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "InsufficientBalance",
    "inputs": [
      {
        "name": "balance",
        "type": "uint256"
      },
      {
        "name": "needed",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidContractAddress",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidDisputeId",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidImplementationIndex",
    "inputs": [
      {
        "name": "index",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidInitialization",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidNumberOfRulingOptions",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidRuling",
    "inputs": [
      {
        "name": "ruling",
        "type": "uint256"
      },
      {
        "name": "max",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotArbitrator",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotEnoughFee",
    "inputs": [
      {
        "name": "sent",
        "type": "uint256"
      },
      {
        "name": "required",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotFactory",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotInitializing",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotOwner",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Panic",
    "inputs": [
      {
        "name": "code",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "PendingOwnerOnly",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReentrancyGuardReentrantCall",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TransferFailed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  },
  {
    "type": "event",
    "name": "ArbitratorSet",
    "inputs": [
      {
        "name": "oldValue",
        "type": "address",
        "indexed": true
      },
      {
        "name": "newValue",
        "type": "address",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Contribution",
    "inputs": [
      {
        "name": "round",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "ruling",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "contributor",
        "type": "address",
        "indexed": true
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "CrowdfundableDisputeDeployed",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "indexed": true
      },
      {
        "name": "instance",
        "type": "address",
        "indexed": true
      },
      {
        "name": "owner",
        "type": "address",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "CrowdfundableDisputeImplementationAdded",
    "inputs": [
      {
        "name": "implementation",
        "type": "address",
        "indexed": true
      },
      {
        "name": "name",
        "type": "string",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "CrowdfundableDisputeImplementationRemoved",
    "inputs": [
      {
        "name": "implementation",
        "type": "address",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "DefaultCrowdfundableDisputeImplementationSet",
    "inputs": [
      {
        "name": "oldDefault",
        "type": "address",
        "indexed": true
      },
      {
        "name": "newDefault",
        "type": "address",
        "indexed": true
      },
      {
        "name": "name",
        "type": "string",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "DefaultDisputeImplementationSet",
    "inputs": [
      {
        "name": "oldDefault",
        "type": "address",
        "indexed": true
      },
      {
        "name": "newDefault",
        "type": "address",
        "indexed": true
      },
      {
        "name": "name",
        "type": "string",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "DefaultsProviderSet",
    "inputs": [
      {
        "name": "oldValue",
        "type": "address",
        "indexed": true
      },
      {
        "name": "newValue",
        "type": "address",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Dispute",
    "inputs": [
      {
        "name": "_arbitrator",
        "type": "address",
        "indexed": true
      },
      {
        "name": "_disputeId",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "_metaEvidenceId",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "_evidenceGroupId",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "DisputeCreated",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "indexed": true
      },
      {
        "name": "providerDisputeId",
        "type": "uint256",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "DisputeCreated",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "indexed": true
      },
      {
        "name": "instance",
        "type": "address",
        "indexed": true
      },
      {
        "name": "owner",
        "type": "address",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "DisputeImplementationAdded",
    "inputs": [
      {
        "name": "implementation",
        "type": "address",
        "indexed": true
      },
      {
        "name": "name",
        "type": "string",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "DisputeImplementationRemoved",
    "inputs": [
      {
        "name": "implementation",
        "type": "address",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "EthRescued",
    "inputs": [
      {
        "name": "to",
        "type": "address",
        "indexed": true
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Evidence",
    "inputs": [
      {
        "name": "_arbitrator",
        "type": "address",
        "indexed": true
      },
      {
        "name": "_evidenceGroupId",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "_party",
        "type": "address",
        "indexed": true
      },
      {
        "name": "_evidence",
        "type": "string",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "FeeConfigSet",
    "inputs": [
      {
        "name": "oldRecipient",
        "type": "address",
        "indexed": true
      },
      {
        "name": "newRecipient",
        "type": "address",
        "indexed": true
      },
      {
        "name": "oldFee",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "newFee",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Initialized",
    "inputs": [
      {
        "name": "version",
        "type": "uint64",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "MetaEvidence",
    "inputs": [
      {
        "name": "_metaEvidenceId",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "_evidence",
        "type": "string",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferInitiated",
    "inputs": [
      {
        "name": "currentOwner",
        "type": "address",
        "indexed": true
      },
      {
        "name": "pendingOwner",
        "type": "address",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferred",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Ruling",
    "inputs": [
      {
        "name": "_arbitrator",
        "type": "address",
        "indexed": true
      },
      {
        "name": "_disputeId",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "_ruling",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RulingByDefault",
    "inputs": [
      {
        "name": "providerDisputeId",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "arbitratorRuling",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "effectiveRuling",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RulingFunded",
    "inputs": [
      {
        "name": "round",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "ruling",
        "type": "uint256",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RulingIssued",
    "inputs": [
      {
        "name": "providerDisputeId",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "ruling",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Withdrawal",
    "inputs": [
      {
        "name": "round",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "ruling",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "contributor",
        "type": "address",
        "indexed": true
      },
      {
        "name": "reward",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "function",
    "name": "DENOMINATOR",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "acceptOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "addCrowdfundableDisputeImpl",
    "inputs": [
      {
        "name": "impl",
        "type": "address"
      },
      {
        "name": "name",
        "type": "string"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "addDisputeImpl",
    "inputs": [
      {
        "name": "impl",
        "type": "address"
      },
      {
        "name": "name",
        "type": "string"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "aggregate3",
    "inputs": [
      {
        "name": "calls",
        "type": "tuple[]",
        "components": [
          {
            "name": "target",
            "type": "address"
          },
          {
            "name": "allowFailure",
            "type": "bool"
          },
          {
            "name": "callData",
            "type": "bytes"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "returnData",
        "type": "tuple[]",
        "components": [
          {
            "name": "success",
            "type": "bool"
          },
          {
            "name": "returnData",
            "type": "bytes"
          }
        ]
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "amendMetaEvidence",
    "inputs": [
      {
        "name": "newUri",
        "type": "string"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "appeal",
    "inputs": [
      {
        "name": "_arbitratorExtraData",
        "type": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "appealCost",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "appealPeriod",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      },
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "arbitrationCost",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "arbitrationCost",
    "inputs": [
      {
        "name": "_extraData",
        "type": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "cost",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "arbitrator",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "arbitratorExtraData",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "contributionOf",
    "inputs": [
      {
        "name": "roundNumber",
        "type": "uint256"
      },
      {
        "name": "contributor",
        "type": "address"
      },
      {
        "name": "rulingOption",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "createCrowdfundableDispute",
    "inputs": [
      {
        "name": "req",
        "type": "tuple",
        "components": [
          {
            "name": "id",
            "type": "bytes32"
          },
          {
            "name": "arbitratorExtraData",
            "type": "bytes"
          },
          {
            "name": "numberOfRulingOptions",
            "type": "uint256"
          },
          {
            "name": "metaEvidenceUri",
            "type": "string"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "instance",
        "type": "address"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "createCrowdfundableDispute",
    "inputs": [
      {
        "name": "impl",
        "type": "address"
      },
      {
        "name": "req",
        "type": "tuple",
        "components": [
          {
            "name": "id",
            "type": "bytes32"
          },
          {
            "name": "arbitratorExtraData",
            "type": "bytes"
          },
          {
            "name": "numberOfRulingOptions",
            "type": "uint256"
          },
          {
            "name": "metaEvidenceUri",
            "type": "string"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "instance",
        "type": "address"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "createDispute",
    "inputs": [
      {
        "name": "req",
        "type": "tuple",
        "components": [
          {
            "name": "id",
            "type": "bytes32"
          },
          {
            "name": "arbitratorExtraData",
            "type": "bytes"
          },
          {
            "name": "numberOfRulingOptions",
            "type": "uint256"
          },
          {
            "name": "metaEvidenceUri",
            "type": "string"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "instance",
        "type": "address"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "createDispute",
    "inputs": [
      {
        "name": "impl",
        "type": "address"
      },
      {
        "name": "req",
        "type": "tuple",
        "components": [
          {
            "name": "id",
            "type": "bytes32"
          },
          {
            "name": "arbitratorExtraData",
            "type": "bytes"
          },
          {
            "name": "numberOfRulingOptions",
            "type": "uint256"
          },
          {
            "name": "metaEvidenceUri",
            "type": "string"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "instance",
        "type": "address"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "creationFee",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "crowdfundableDisputeImplementationAt",
    "inputs": [
      {
        "name": "index",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "impl",
        "type": "address"
      },
      {
        "name": "name",
        "type": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "crowdfundableDisputeImplementationCount",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "defaultCrowdfundableDisputeImplementation",
    "inputs": [],
    "outputs": [
      {
        "name": "impl",
        "type": "address"
      },
      {
        "name": "name",
        "type": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "defaultDisputeImplementation",
    "inputs": [],
    "outputs": [
      {
        "name": "impl",
        "type": "address"
      },
      {
        "name": "name",
        "type": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "defaultsProvider",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "disputeImplementationAt",
    "inputs": [
      {
        "name": "index",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "impl",
        "type": "address"
      },
      {
        "name": "name",
        "type": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "disputeImplementationCount",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "evidenceSubmitted",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "factory",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "feeRecipient",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "fundAppeal",
    "inputs": [
      {
        "name": "rulingOption",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "getDispute",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes"
      },
      {
        "name": "",
        "type": "uint256"
      },
      {
        "name": "",
        "type": "uint256"
      },
      {
        "name": "",
        "type": "uint256"
      },
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getMultipliers",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      },
      {
        "name": "",
        "type": "uint256"
      },
      {
        "name": "",
        "type": "uint256"
      },
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getRound",
    "inputs": [
      {
        "name": "roundNumber",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256[]"
      },
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getRuling",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      },
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getTotalWithdrawableAmount",
    "inputs": [
      {
        "name": "contributor",
        "type": "address"
      },
      {
        "name": "rulingOption",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "sum",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "initialize",
    "inputs": [
      {
        "name": "_owner",
        "type": "address"
      },
      {
        "name": "_arbitratorExtraData",
        "type": "bytes"
      },
      {
        "name": "_metaEvidenceUri",
        "type": "string"
      },
      {
        "name": "_numberOfRulingOptions",
        "type": "uint256"
      },
      {
        "name": "_creationFee",
        "type": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "isCreateCrowdfundableDisputeRequestValid",
    "inputs": [
      {
        "name": "req",
        "type": "tuple",
        "components": [
          {
            "name": "id",
            "type": "bytes32"
          },
          {
            "name": "arbitratorExtraData",
            "type": "bytes"
          },
          {
            "name": "numberOfRulingOptions",
            "type": "uint256"
          },
          {
            "name": "metaEvidenceUri",
            "type": "string"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "predicted",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isCreateCrowdfundableDisputeRequestValid",
    "inputs": [
      {
        "name": "impl",
        "type": "address"
      },
      {
        "name": "req",
        "type": "tuple",
        "components": [
          {
            "name": "id",
            "type": "bytes32"
          },
          {
            "name": "arbitratorExtraData",
            "type": "bytes"
          },
          {
            "name": "numberOfRulingOptions",
            "type": "uint256"
          },
          {
            "name": "metaEvidenceUri",
            "type": "string"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "predicted",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isCreateDisputeRequestValid",
    "inputs": [
      {
        "name": "req",
        "type": "tuple",
        "components": [
          {
            "name": "id",
            "type": "bytes32"
          },
          {
            "name": "arbitratorExtraData",
            "type": "bytes"
          },
          {
            "name": "numberOfRulingOptions",
            "type": "uint256"
          },
          {
            "name": "metaEvidenceUri",
            "type": "string"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "predicted",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isCreateDisputeRequestValid",
    "inputs": [
      {
        "name": "impl",
        "type": "address"
      },
      {
        "name": "req",
        "type": "tuple",
        "components": [
          {
            "name": "id",
            "type": "bytes32"
          },
          {
            "name": "arbitratorExtraData",
            "type": "bytes"
          },
          {
            "name": "numberOfRulingOptions",
            "type": "uint256"
          },
          {
            "name": "metaEvidenceUri",
            "type": "string"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "predicted",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isFullyFunded",
    "inputs": [
      {
        "name": "roundNumber",
        "type": "uint256"
      },
      {
        "name": "rulingOption",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isRuled",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "loserAppealPeriodMultiplier",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "loserStakeMultiplier",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "multiplierDefaultsProvider",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "multiplierProvider",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "numberOfRulingOptions",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "paidFees",
    "inputs": [
      {
        "name": "roundNumber",
        "type": "uint256"
      },
      {
        "name": "rulingOption",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pendingOwner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "predictCrowdfundableDisputeAddress",
    "inputs": [
      {
        "name": "req",
        "type": "tuple",
        "components": [
          {
            "name": "id",
            "type": "bytes32"
          },
          {
            "name": "arbitratorExtraData",
            "type": "bytes"
          },
          {
            "name": "numberOfRulingOptions",
            "type": "uint256"
          },
          {
            "name": "metaEvidenceUri",
            "type": "string"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "predicted",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "predictCrowdfundableDisputeAddress",
    "inputs": [
      {
        "name": "impl",
        "type": "address"
      },
      {
        "name": "req",
        "type": "tuple",
        "components": [
          {
            "name": "id",
            "type": "bytes32"
          },
          {
            "name": "arbitratorExtraData",
            "type": "bytes"
          },
          {
            "name": "numberOfRulingOptions",
            "type": "uint256"
          },
          {
            "name": "metaEvidenceUri",
            "type": "string"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "predicted",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "predictDisputeAddress",
    "inputs": [
      {
        "name": "req",
        "type": "tuple",
        "components": [
          {
            "name": "id",
            "type": "bytes32"
          },
          {
            "name": "arbitratorExtraData",
            "type": "bytes"
          },
          {
            "name": "numberOfRulingOptions",
            "type": "uint256"
          },
          {
            "name": "metaEvidenceUri",
            "type": "string"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "predicted",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "predictDisputeAddress",
    "inputs": [
      {
        "name": "impl",
        "type": "address"
      },
      {
        "name": "req",
        "type": "tuple",
        "components": [
          {
            "name": "id",
            "type": "bytes32"
          },
          {
            "name": "arbitratorExtraData",
            "type": "bytes"
          },
          {
            "name": "numberOfRulingOptions",
            "type": "uint256"
          },
          {
            "name": "metaEvidenceUri",
            "type": "string"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "predicted",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "providerDisputeId",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "removeCrowdfundableDisputeImpl",
    "inputs": [
      {
        "name": "impl",
        "type": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "removeDisputeImpl",
    "inputs": [
      {
        "name": "impl",
        "type": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "rescueEth",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "roundCount",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "rule",
    "inputs": [
      {
        "name": "_providerDisputeId",
        "type": "uint256"
      },
      {
        "name": "_ruling",
        "type": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "ruling",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setArbitrator",
    "inputs": [
      {
        "name": "newArb",
        "type": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setDefaultCrowdfundableDisputeImpl",
    "inputs": [
      {
        "name": "impl",
        "type": "address"
      },
      {
        "name": "name",
        "type": "string"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setDefaultDisputeImpl",
    "inputs": [
      {
        "name": "impl",
        "type": "address"
      },
      {
        "name": "name",
        "type": "string"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setDefaultsProvider",
    "inputs": [
      {
        "name": "newProvider",
        "type": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setFeeConfig",
    "inputs": [
      {
        "name": "newRecipient",
        "type": "address"
      },
      {
        "name": "newFee",
        "type": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "submitEvidence",
    "inputs": [
      {
        "name": "_evidenceUri",
        "type": "string"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "sweep",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "transferOwnership",
    "inputs": [
      {
        "name": "newOwner",
        "type": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "winnerStakeMultiplier",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "withdrawFeesAndRewards",
    "inputs": [
      {
        "name": "contributor",
        "type": "address"
      },
      {
        "name": "roundNumber",
        "type": "uint256"
      },
      {
        "name": "rulingOption",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "amount",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "withdrawFeesAndRewardsForAllRounds",
    "inputs": [
      {
        "name": "contributor",
        "type": "address"
      },
      {
        "name": "rulingOption",
        "type": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  }
] as const;

export const EVENT_TOPICS = {
  "DisputeCreated": "0x0cb2985c5989c5947b9f1fd133799cc0d5da450f2493d3ea7cb48a0c96ca1d0b",
  "CrowdfundableDisputeDeployed": "0x76938d802bea77bf524b5eeec4f8494f2b58b42a3a9117db130d7aed38b33dea",
  "ProviderDisputeCreated": "0x3fe8d10fd802469ff2d30bb2e9743433b98db16950c5a1570663d3a11f57720b",
  "RulingIssued": "0x092bca40185341e69f5cd5e7310391d34d444384b865e4db3a041b52c578613c",
  "Evidence": "0xdccf2f8b2cc26eafcd61905cba744cff4b81d14740725f6376390dc6298a6a3c"
} as const;
